name: ars_news
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  shared_preferences: ^2.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/beritatek1.jpeg
   - assets/beritatek2.jpeg
   - assets/beritatek3.jpeg
   - assets/beritakul1.jpeg
   - assets/beritakul2.jpeg
   - assets/beritacu1.jpg
   - assets/beritacu2.jpeg

